---
title: Organizr
author: CauseFX
email: causefx@me.com
description: Do you have quite a bit of services running on your computer or server?
  Do you have a lot of bookmarks or have to memorize a bunch of ip's and ports? Well,
  Organizr is here to help with that. Organizr allows you to setup "Tabs" that will
  be loaded all in one webpage. You can then work on your server with ease. Want to
  give users access to some Tabs? No problem, just enable user support and have them
  make an account. Want guests to be able to visit too? Enable Guest support for those
  tabs.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
